USE MASTER;
DROP DATABASE ClanWars;
CREATE DATABASE ClanWars;
USE ClanWars;


CREATE TABLE Clan (
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	name NVARCHAR(50) NOT NULL,
	motto NVARCHAR(100),
	gold INT DEFAULT 0,
	lumber INT DEFAULT 0,
	food INT DEFAULT 0,
	soldier INT DEFAULT 0
);


CREATE TABLE Building (
	id VARCHAR(50) NOT NULL PRIMARY KEY,
	name NVARCHAR(50) NOT NULL
);

CREATE TABLE ClanBuilding(
	clan INT NOT NULL FOREIGN KEY REFERENCES Clan(id) ON DELETE CASCADE,
	building VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES Building(id),
	count INT NOT NULL DEFAULT 0, /* this is level in EERD*/
	percentage INT NOT NULL DEFAULT 0,
	is_under_upgrade BIT DEFAULT 0,
	CONSTRAINT PK_ClanBuilding PRIMARY KEY ([building], [clan])
);

CREATE TABLE War (
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY
);

CREATE TABLE WarLog (
	war INT NOT NULL FOREIGN KEY REFERENCES War(id) ON DELETE CASCADE,
	clan INT NOT NULL FOREIGN KEY REFERENCES Clan(id) ON DELETE CASCADE,
	experience INT NOT NULL,
	gold INT NOT NULL,
	food INT NOT NULL,
	soldier INT NOT NULL,
	winner BIT NOT NULL,
);

CREATE TABLE Player ( /* User is a reserved word! */
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	name NVARCHAR(50) NOT NULL,
	clan INT FOREIGN KEY REFERENCES Clan(id)
);

CREATE TABLE Role (
	id VARCHAR(50) NOT NULL PRIMARY KEY,
	name NVARCHAR(50) NOT NULL
);

CREATE TABLE Job (
	id VARCHAR(50) NOT NULL PRIMARY KEY,
	name NVARCHAR(50) NOT NULL
);

CREATE TABLE PlayerJob (
	player INT NOT NULL FOREIGN KEY REFERENCES Player(id) ON DELETE CASCADE,
	job VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES Job(id) ON DELETE CASCADE,
	level INT NOT NULL DEFAULT 1,
	exp INT NOT NULL DEFAULT 10,
	CONSTRAINT PK_PlayerJob PRIMARY KEY ([player], [job])
);

CREATE TABLE PlayerClanRoleJob (
	player INT NOT NULL FOREIGN KEY REFERENCES Player(id) ON DELETE CASCADE,
	clan INT NOT NULL FOREIGN KEY REFERENCES Clan(id) ON DELETE CASCADE,
	role VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES Role(id) ON DELETE CASCADE,
	job VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES Job(id) ON DELETE CASCADE,
	CONSTRAINT PK_PlayerClanRoleJob PRIMARY KEY ([player], [clan])
);

